name: Build NetHunter Kernel for Redmi 9A (Android 10)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev libncurses5-dev ccache

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
        unzip android-ndk-r26d-linux.zip
        mv android-ndk-r26d $HOME/android-ndk
        echo "export PATH=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-
        export ANDROID_MAJOR_VERSION=q
        make your_defconfig
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nethunter-kernel
        path: arch/arm64/boot/Image.gz-dtb
