- name: Auto-find and download defconfig
  run: |
    echo "🔍 Ищем dandelion_defconfig..."
    FILE_URL=$(curl -s https://api.github.com/repos/MiCode/Xiaomi_Kernel_OpenSource/contents/arch/arm64/configs?ref=dandelion-q-oss \
      | grep '"download_url":' \
      | grep dandelion_defconfig \
      | cut -d '"' -f 4)

    if [ -z "$FILE_URL" ]; then
      echo "❌ Не удалось найти dandelion_defconfig в репозитории Xiaomi."
      exit 1
    fi

    echo "✅ Скачали конфигурацию: $FILE_URL"
    wget "$FILE_URL" -O arch/arm64/configs/nethunter_defconfig
