name: Build NetHunter Kernel for Redmi 9A (Android 10)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev libncurses5-dev ccache wget unzip zip git

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
        unzip android-ndk-r26d-linux.zip
        mv android-ndk-r26d $HOME/android-ndk
        echo "$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Replace defconfig
      run: |
        cp nethunter_defconfig arch/arm64/configs/
        echo "✅ nethunter_defconfig copied."

    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-
        export ANDROID_MAJOR_VERSION=q
        make nethunter_defconfig
        make -j$(nproc)

    - name: Prepare AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git
        cp arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 ../nethunter-kernel-flashable.zip ./*

    - name: Upload flashable ZIP
      uses: actions/upload-artifact@v4
      with:
        name: nethunter-kernel-flashable
        path: nethunter-kernel-flashable.zip
