name: Build NetHunter Kernel for Redmi 9A

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev make gcc g++ zip git wget curl python3

      - name: Clone Xiaomi kernel (dandelion-q-oss)
        run: |
          git clone --depth=1 -b dandelion-q-oss https://github.com/MiCode/Xiaomi_Kernel_OpenSource kernel

      - name: Download GCC toolchain (AArch64)
        run: |
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 gcc-arm64
          echo "$GITHUB_WORKSPACE/gcc-arm64/bin" >> $GITHUB_PATH

      - name: Configure kernel (dandelion_defconfig)
        working-directory: kernel
        env:
          ARCH: arm64
          SUBARCH: arm64
          CROSS_COMPILE: ${{ github.workspace }}/gcc-arm64/bin/aarch64-linux-android-
        run: |
          make O=out dandelion_defconfig

      - name: Apply NetHunter config (HID + Wi-Fi modules)
        working-directory: kernel
        env:
          ARCH: arm64
          SUBARCH: arm64
          CROSS_COMPILE: ${{ github.workspace }}/gcc-arm64/bin/aarch64-linux-android-
        run: |
          # Создаём фрагмент с нужными настройками
          cat > nethunter.config << 'EOF'
          # USB HID gadget
          CONFIG_USB_CONFIGFS=y
          CONFIG_USB_CONFIGFS_HID=y
          CONFIG_USB_F_HID=m
          CONFIG_USB_G_HID=m

          # Wi-Fi drivers for external adapters (monitor/injection)
          CONFIG_ATH9K_HTC=m
          CONFIG_RTL8187=m
          CONFIG_RTL8XXXU=m
          CONFIG_RTL8192CU=m
          CONFIG_RTL8192EU=m
          CONFIG_RTL8723BU=m
          CONFIG_MT7601U=m
          CONFIG_RT2800USB=m
          CONFIG_RT73USB=m

          # Networking prerequisites
          CONFIG_PACKET=y
          CONFIG_NETFILTER=y
          CONFIG_NF_TABLES=y
          EOF

          # Сливаем фрагмент в текущий .config и обновляем
          cat nethunter.config >> out/.config || true
          yes "" | make O=out olddefconfig

      - name: Build kernel
        working-directory: kernel
        env:
          ARCH: arm64
          SUBARCH: arm64
          CROSS_COMPILE: ${{ github.workspace }}/gcc-arm64/bin/aarch64-linux-android-
        run: |
          make O=out -j$(nproc)

      - name: Pack with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3 AnyKernel3
          # Копируем собранное ядро; для этого девайса достаточно Image.gz-dtb
          cp kernel/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cd AnyKernel3
          zip -r9 "kernel-nethunter deepcomon (dandelion).zip" * -x .git* README*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-nethunter deepcomon (dandelion)
          path: AnyKernel3/kernel-nethunter deepcomon (dandelion).zip
