name: Build NetHunter Kernel for Redmi 9A (Android 10)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make \
        gcc clang libncurses-dev wget unzip python3 git zip openjdk-11-jre-headless

    - name: Set build date
      run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip android-ndk-r25c-linux.zip
        mv android-ndk-r25c $HOME/android-ndk

    - name: Download nethunter_defconfig for Redmi 9A
      run: |
        wget https://raw.githubusercontent.com/MiCode/Xiaomi_Kernel_OpenSource/dandelion-q-oss/arch/arm64/configs/dandelion_defconfig \
          -O arch/arm64/configs/nethunter_defconfig

    - name: Build kernel
      run: |
        export PATH=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        make O=out ARCH=arm64 nethunter_defconfig
        make -j$(nproc) O=out ARCH=arm64 \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Prepare AnyKernel3 ZIP
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 ../NetHunter-Redmi9A-${BUILD_DATE}-unsigned.zip ./*

    - name: Download testkeys for signing
      run: |
        wget https://raw.githubusercontent.com/apkmirror/ApkSignatureTools/master/testkey.x509.pem
        wget https://raw.githubusercontent.com/apkmirror/ApkSignatureTools/master/testkey.pk8

    - name: Download signapk tool
      run: |
        wget https://raw.githubusercontent.com/lineageos/android_build/master/tools/signapk/signapk.jar

    - name: Sign flashable ZIP
      run: |
        java -jar signapk.jar testkey.x509.pem testkey.pk8 NetHunter-Redmi9A-${BUILD_DATE}-unsigned.zip NetHunter-Redmi9A-${BUILD_DATE}.zip

    - name: Upload signed flashable ZIP
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-Redmi9A-${{ env.BUILD_DATE }}
        path: NetHunter-Redmi9A-${{ env.BUILD_DATE }}.zip
